### ISSUE TITLE
verbosity parameter in TVART_alt_min.m

### ISSUE THREAD

**Issue by prateekgv** [kharris/tvart#2]
In the TVART_alt_min.m file, the verbosity variable is used to reset the spatial and temporal modes, i.e., A, B, and C. If the TVART uses alternating minimization technique and every optimization problem is convex in either A/B/C, then shouldn't the cost function decrease at every step? It is not clear why verbosity variable is used to reset the A/B/C in the code. Also, resetting A, B, C was not mentioned in the paper.

**Comment by kamdh** [comment]
Hi @prateekgv 

I looked back at the code just and don't see any effect on the verbosity except to add print statements and perhaps calculate the cost.

Leaving open for now in case you can add more details to your concern.

Thanks

**Comment by prateekgv** [comment]
Hi @kamdh, thanks for your response. In the code below:

>         old_A = A;
>         old_c = c;
>         A = solve_A(X, Y, A, B, C, N, M, T, r, eta, proximal);
>         if verbosity >= 2
>             [c,rmse] = cost(X, Y, A, B, C, N, M, T, r,...
>                             eta, beta, regularization, proximal);
>             fprintf('\tpost A solve: cost = %1.5g, RMSE = %1.3g\n', ...
>                     c, rmse);
>         end
>         if old_c < c
>             fprintf(['Warning: not updating A because cost went up!\' ...
>                      'n']);
>             A = old_A;
>             c = old_c;
>         end

If the `verbosity` parameter is set to 2, you compute the cost `c` after updating `A` or `B` or `C`. If the cost function is convex in any of those variables, then `c` after solving for `A` should be smaller than `c` before solving for `A`. Why do you need the `warning` step where you compare the `old_c` and `c` and only update `A` if the cost goes down? Note that this is true only when `verbosity` is set to 2. Shouldn't `c` always go down after updating each of either `A` or `B` or `C`?

**Comment by kamdh** [comment]
Hi @prateekgv,
You're right that the cost shouldn't go up since things are convex. However, sometimes numerical errors creep into these "solve_" steps and the solutions explode, which that test can check. I think when the algorithm is converging, those steps don't get triggered. Also, it could be this is a remnant leftover from when I was developing the method. I don't entirely remember.
